import apiClient from "../api/client";

// POST /api/auth/login
// credentials: { email, password, expectedRole }
export async function login(credentials) {
  const response = await apiClient.post("/auth/login", {
    email:    credentials.email,
    password: credentials.password,
    role:     credentials.expectedRole, // backend uses 'role' key
  });
  return response.data; // { token, user }
}

// POST /api/auth/register
// payload: { full_name, email, phone, password }
// user_id is auto-generated by Oracle sequence — not sent from frontend
export async function register(payload) {
  const response = await apiClient.post("/auth/register", {
    full_name: payload.full_name,
    email:     payload.email,
    phone:     payload.phone || "",
    password:  payload.password,
  });
  return response.data; // { token, user }
}
