const express = require("express");
const bcrypt  = require("bcryptjs");
const jwt     = require("jsonwebtoken");
const { execute } = require("../db");

const router = express.Router();

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeToken(row) {
  return jwt.sign(
    { id: row.USER_ID, user_id: row.USER_ID, role: row.ROLE },
    process.env.JWT_SECRET,
    { expiresIn: process.env.JWT_EXPIRES_IN || "8h" }
  );
}

function mapUser(row) {
  return {
    id:        row.USER_ID,
    user_id:   row.USER_ID,
    name:      row.FULL_NAME,
    full_name: row.FULL_NAME,
    email:     row.EMAIL,
    phone:     row.PHONE,
    role:      row.ROLE,
    status:    row.STATUS,
  };
}

// ─── POST /api/auth/login ─────────────────────────────────────────────────────
// Login by email + password (schema uses column name: password)
router.post("/login", async (req, res) => {
  try {
    const { email, password, role } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "Email and password are required." });
    }

    // Schema column is 'password' (not password_hash)
    const result = await execute(
      `SELECT user_id, full_name, email, phone, password, role, status
         FROM users WHERE LOWER(email) = LOWER(:email)`,
      { email: email.trim() }
    );

    const row = result.rows?.[0];
    if (!row) return res.status(401).json({ error: "Invalid email or password." });
    if (row.STATUS !== "active") return res.status(403).json({ error: "Account is inactive." });

    const match = await bcrypt.compare(password, row.PASSWORD);
    if (!match) return res.status(401).json({ error: "Invalid email or password." });

    if (role && row.ROLE !== role) {
      return res.status(403).json({
        error: role === "admin"
          ? "This account does not have admin access."
          : "Admin accounts must use the admin login.",
      });
    }

    return res.json({ token: makeToken(row), user: mapUser(row) });
  } catch (err) {
    console.error("Login error:", err);
    return res.status(500).json({ error: "Login failed." });
  }
});

// ─── POST /api/auth/register ──────────────────────────────────────────────────
// user_id is auto-generated by Oracle sequence trigger.
// Schema column: password (not password_hash), no created_at column.
router.post("/register", async (req, res) => {
  try {
    const { full_name, email, phone, password } = req.body;

    if (!full_name || !email || !password) {
      return res.status(400).json({ error: "Full name, email, and password are required." });
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
      return res.status(400).json({ error: "Invalid email format." });
    }
    if (password.length < 6) {
      return res.status(400).json({ error: "Password must be at least 6 characters." });
    }

    const exists = await execute(
      `SELECT COUNT(*) AS cnt FROM users WHERE LOWER(email) = LOWER(:email)`,
      { email: email.trim() }
    );
    if (Number(exists.rows[0].CNT) > 0) {
      return res.status(409).json({ error: "An account with this email already exists." });
    }

    const hash = await bcrypt.hash(password, 10);

    // Insert without user_id (trigger fills it from sequence)
    // No created_at column in new schema
    await execute(
      `INSERT INTO users (full_name, email, phone, password, role, status)
       VALUES (:name, :email, :phone, :hash, 'user', 'active')`,
      {
        name:  full_name.trim(),
        email: email.trim(),
        phone: phone ? phone.trim() : null,
        hash,
      },
      { autoCommit: true }
    );

    const created = await execute(
      `SELECT user_id, full_name, email, phone, role, status
         FROM users WHERE LOWER(email) = LOWER(:email)`,
      { email: email.trim() }
    );
    const newUser = created.rows[0];
    return res.status(201).json({ token: makeToken(newUser), user: mapUser(newUser) });
  } catch (err) {
    console.error("Register error:", err);
    return res.status(500).json({ error: "Registration failed." });
  }
});

module.exports = router;
